---
config:
  look: neo
  theme: mc
---
graph LR
    A[Компиляция<br>модели]
    A1[Компиляция DD<br>из модели]
    A2[Компиляция DDL<br>инкрементального<br>обновления]
    A --> |Первый запуск| A1
    A --> |"Последующие<br>запуски<br>(инкрементальные)"| A2
    subgraph База данных
        M[Обычная<br>материализация<br>через временную<br>таблицу]
        B[Создание временной<br>таблицы *__dbt_tmp]
        C[Вставка данных<br>в таблицу<br>из временной<br>таблицы]
        D[Удаление<br>временной<br>таблицы]
    end
    A1 --> M
    A2 --> B -->|Успешно| C --> D
    B -->|Ошибка| D
