---
config:
  look: neo
  theme: mc
---
graph LR
    A[Компиляция<br>модели в DDL]
    subgraph База данных
        B[Создание временной<br>таблицы *__dbt_tmp]
        C[Пересоздание таблицы<br>из временной таблицы]
        D[Удаление временной<br>таблицы]
    end
    A --> B -->|Успешно| C --> D
    B -->|Ошибка| D